### ISSUE TITLE
Segfault when accessing large converted matrix

### ISSUE THREAD

**Issue by Dniskk** [RUrlus/carma#67] opened 2020-10-01 15:09 UTC
I use the following code to generate a matrix: 

    import numpy as np
    from numpy.random import multivariate_normal

    mean = [0] * 5000
    sigma = np.eye(5000, 5000)
    X = multivariate_normal(mean=mean, cov=sigma, size=5000)

Unfortunately, the following function throws a segfault:

    void padmWrapper(py::array_t<double> &X, py::array_t<double> &y) {
        py::print(X);
        arma::mat XA = carma::arr_to_mat<double>(X);
        arma::vec yA = carma::arr_to_col<double>(y);
        std::cout << "Cols: " << XA.n_cols << ", Rows: " << XA.n_rows << "\n";
        for (size_t i=0; i<XA.n_cols; ++i) {
            for (size_t j=0; j<XA.n_rows; ++j) {
                 std::cout << XA.at(j, i) << "\n";
            }
        }
        ...
    }

`py::print(X)` works correctly, no error is thrown when the matrix is converted and the number of columns and rows is also printed correctly. But once I access an element in `XA` a segfault is caused. When I generate a smaller matrix (e.g. 100 times 100) the conversion works correctly and no error occurs.

The code ran on an Ubuntu machine. 

### Edit:
Generating the matrix as follows does **not** produce the issue:

    import numpy as np
    from numpy.random import multivariate_normal

    mean = [0] * 5000
    sigma = np.eye(5000, 5000)
    X = np.asfortranarray(multivariate_normal(mean=mean, cov=sigma, size=5000))

So that gives me a workaround for the moment. I suspect that there is a problem when the underlying data must be copied.

**Comment by RUrlus** [comment] 2020-10-04 15:42
Thanks for the report, I can reproduce locally as well with row-contiguous arrays.

The difference indeed being that C style arrays are copied.
It may be a reference count issue that only shows up because the larger memory is being recycled earlier than with small arrays. I am looking into it.

**Comment by RUrlus** [comment] 2021-01-07 13:19
Bug was caused by internal copy of C-contiguous arrays being destructed, solved in 3a292df7d42212a5b9ff001ac9806aa93f5784d0 for *NIX based systems.

**Comment by RUrlus** [comment] 2021-03-19 18:33
Resolved in b1594476f5f136a9d3b2289123d94a51fc924692

**Closed** 2021-03-19 18:35 UTC
Labels: bug
